/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.LibrarySystem.GUI;

import com.LibrarySystem.Database.LibroDB;
import com.LibrarySystem.Entities.Libro;
import com.LibrarySystem.Entities.Seguridad;
import com.LibrarySystem.Entities.Usuario;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author brayan
 */
public class DetallesLibro extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public DetallesLibro() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    
    public void mostrarDetalle (int id_libro){
        ArrayList<Libro> list_libro = new ArrayList<>();
        LibroDB libro = new  LibroDB ();
        try {
            list_libro = libro.obtenerLibroByLibro(id_libro);
            label_titulo.setText(list_libro.get(0).toString());
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(DetallesLibro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBody = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblGestionarUsuarios = new javax.swing.JLabel();
        lblGestionarBibliotecas = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        lblAtras = new javax.swing.JLabel();
        label_titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblGestionarUsuarios2 = new javax.swing.JLabel();
        lblGestionarUsuarios3 = new javax.swing.JLabel();
        lblGestionarUsuarios4 = new javax.swing.JLabel();
        lblGestionarUsuarios5 = new javax.swing.JLabel();
        lblGestionarUsuarios6 = new javax.swing.JLabel();
        lblGestionarUsuarios7 = new javax.swing.JLabel();
        lblGestionarUsuarios8 = new javax.swing.JLabel();
        lblGestionarUsuarios9 = new javax.swing.JLabel();
        btnTomarPrestado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlBody.setBackground(new java.awt.Color(52, 73, 94));

        pnlHeader.setBackground(new java.awt.Color(23, 165, 137));

        lblTitulo.setBackground(java.awt.Color.white);
        lblTitulo.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblTitulo.setForeground(java.awt.Color.white);
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/LibrarySystem/Icons/user-white.png"))); // NOI18N
        lblTitulo.setText("Detalles Libro");

        lblCerrar.setBackground(java.awt.Color.white);
        lblCerrar.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblCerrar.setForeground(java.awt.Color.white);
        lblCerrar.setText("X");
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        lblMinimizar.setBackground(java.awt.Color.white);
        lblMinimizar.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblMinimizar.setForeground(java.awt.Color.white);
        lblMinimizar.setText("-");
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });

        lblGestionarUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        lblGestionarUsuarios.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblGestionarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        lblGestionarUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestionarUsuarios.setText("Gestionar Usuarios");
        lblGestionarUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGestionarUsuariosMouseClicked(evt);
            }
        });

        lblGestionarBibliotecas.setBackground(new java.awt.Color(255, 255, 255));
        lblGestionarBibliotecas.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblGestionarBibliotecas.setForeground(new java.awt.Color(255, 255, 255));
        lblGestionarBibliotecas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestionarBibliotecas.setText("Gestionar Bibliotecas");
        lblGestionarBibliotecas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGestionarBibliotecasMouseClicked(evt);
            }
        });

        lblSalir.setBackground(new java.awt.Color(255, 255, 255));
        lblSalir.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(255, 255, 255));
        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setText("Salir");
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addComponent(lblGestionarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblGestionarBibliotecas, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSalir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 574, Short.MAX_VALUE)
                        .addComponent(lblMinimizar)
                        .addGap(18, 18, 18)
                        .addComponent(lblCerrar)
                        .addGap(22, 22, 22))))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(lblCerrar)
                    .addComponent(lblMinimizar))
                .addGap(18, 18, 18)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGestionarUsuarios)
                    .addComponent(lblGestionarBibliotecas)
                    .addComponent(lblSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblAtras.setBackground(new java.awt.Color(255, 255, 255));
        lblAtras.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblAtras.setForeground(new java.awt.Color(255, 255, 255));
        lblAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/LibrarySystem/Icons/back-white.png"))); // NOI18N
        lblAtras.setText("Atras");
        lblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtrasMouseClicked(evt);
            }
        });

        label_titulo.setBackground(new java.awt.Color(255, 255, 255));
        label_titulo.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        label_titulo.setForeground(new java.awt.Color(255, 255, 255));
        label_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_titulo.setText("Titulo Libro");
        label_titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_tituloMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        lblGestionarUsuarios2.setBackground(new java.awt.Color(255, 255, 255));
        lblGestionarUsuarios2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblGestionarUsuarios2.setForeground(new java.awt.Color(255, 255, 255));
        lblGestionarUsuarios2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestionarUsuarios2.setText("Descripción:");
        lblGestionarUsuarios2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGestionarUsuarios2MouseClicked(evt);
            }
        });

        lblGestionarUsuarios3.setBackground(new java.awt.Color(255, 255, 255));
        lblGestionarUsuarios3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblGestionarUsuarios3.setForeground(new java.awt.Color(255, 255, 255));
        lblGestionarUsuarios3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGestionarUsuarios3.setText("<html>Descripción del Libro</html>");
        lblGestionarUsuarios3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGestionarUsuarios3MouseClicked(evt);
            }
        });

        lblGestionarUsuarios4.setBackground(new java.awt.Color(255, 255, 255));
        lblGestionarUsuarios4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblGestionarUsuarios4.setForeground(new java.awt.Color(255, 255, 255));
        lblGestionarUsuarios4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestionarUsuarios4.setText("Ubicación:");
        lblGestionarUsuarios4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGestionarUsuarios4MouseClicked(evt);
            }
        });

        lblGestionarUsuarios5.setBackground(new java.awt.Color(255, 255, 255));
        lblGestionarUsuarios5.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblGestionarUsuarios5.setForeground(new java.awt.Color(255, 255, 255));
        lblGestionarUsuarios5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGestionarUsuarios5.setText("<html>Ubicación del Libro</html>");
        lblGestionarUsuarios5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGestionarUsuarios5MouseClicked(evt);
            }
        });

        lblGestionarUsuarios6.setBackground(new java.awt.Color(255, 255, 255));
        lblGestionarUsuarios6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblGestionarUsuarios6.setForeground(new java.awt.Color(255, 255, 255));
        lblGestionarUsuarios6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestionarUsuarios6.setText("Categorias:");
        lblGestionarUsuarios6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGestionarUsuarios6MouseClicked(evt);
            }
        });

        lblGestionarUsuarios7.setBackground(new java.awt.Color(255, 255, 255));
        lblGestionarUsuarios7.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblGestionarUsuarios7.setForeground(new java.awt.Color(255, 255, 255));
        lblGestionarUsuarios7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGestionarUsuarios7.setText("<html>Categorias del Libro</html>");
        lblGestionarUsuarios7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGestionarUsuarios7MouseClicked(evt);
            }
        });

        lblGestionarUsuarios8.setBackground(new java.awt.Color(255, 255, 255));
        lblGestionarUsuarios8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblGestionarUsuarios8.setForeground(new java.awt.Color(255, 255, 255));
        lblGestionarUsuarios8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestionarUsuarios8.setText("Autor:");
        lblGestionarUsuarios8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGestionarUsuarios8MouseClicked(evt);
            }
        });

        lblGestionarUsuarios9.setBackground(new java.awt.Color(255, 255, 255));
        lblGestionarUsuarios9.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblGestionarUsuarios9.setForeground(new java.awt.Color(255, 255, 255));
        lblGestionarUsuarios9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGestionarUsuarios9.setText("<html>Autor del Libro</html>");
        lblGestionarUsuarios9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGestionarUsuarios9MouseClicked(evt);
            }
        });

        btnTomarPrestado.setBackground(new java.awt.Color(23, 165, 137));
        btnTomarPrestado.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnTomarPrestado.setForeground(new java.awt.Color(255, 255, 255));
        btnTomarPrestado.setText("Tomar Prestado");
        btnTomarPrestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomarPrestadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
        pnlBody.setLayout(pnlBodyLayout);
        pnlBodyLayout.setHorizontalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(label_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                        .addComponent(lblAtras)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGestionarUsuarios2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGestionarUsuarios4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGestionarUsuarios6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGestionarUsuarios8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGestionarUsuarios9)
                            .addComponent(lblGestionarUsuarios7)
                            .addComponent(lblGestionarUsuarios5)
                            .addComponent(lblGestionarUsuarios3)))
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTomarPrestado)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlBodyLayout.setVerticalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAtras)
                .addGap(18, 18, 18)
                .addComponent(label_titulo)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGestionarUsuarios2)
                            .addComponent(lblGestionarUsuarios3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGestionarUsuarios4)
                            .addComponent(lblGestionarUsuarios5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGestionarUsuarios6)
                            .addComponent(lblGestionarUsuarios7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGestionarUsuarios8)
                            .addComponent(lblGestionarUsuarios9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(73, 73, 73)))
                .addComponent(btnTomarPrestado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblGestionarUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarUsuariosMouseClicked
        
    }//GEN-LAST:event_lblGestionarUsuariosMouseClicked

    private void lblGestionarBibliotecasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarBibliotecasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblGestionarBibliotecasMouseClicked

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro?", "Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        if(resp == 0){
            Login login = new Login();
            login.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAtrasMouseClicked

    private void label_tituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_tituloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_label_tituloMouseClicked

    private void lblGestionarUsuarios2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarUsuarios2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblGestionarUsuarios2MouseClicked

    private void lblGestionarUsuarios3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarUsuarios3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblGestionarUsuarios3MouseClicked

    private void lblGestionarUsuarios4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarUsuarios4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblGestionarUsuarios4MouseClicked

    private void lblGestionarUsuarios5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarUsuarios5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblGestionarUsuarios5MouseClicked

    private void lblGestionarUsuarios6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarUsuarios6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblGestionarUsuarios6MouseClicked

    private void lblGestionarUsuarios7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarUsuarios7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblGestionarUsuarios7MouseClicked

    private void lblGestionarUsuarios8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarUsuarios8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblGestionarUsuarios8MouseClicked

    private void lblGestionarUsuarios9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarUsuarios9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblGestionarUsuarios9MouseClicked

    private void btnTomarPrestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomarPrestadoActionPerformed


    }//GEN-LAST:event_btnTomarPrestadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetallesLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetallesLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetallesLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetallesLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetallesLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTomarPrestado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JLabel lblAtras;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblGestionarBibliotecas;
    private javax.swing.JLabel lblGestionarUsuarios;
    private javax.swing.JLabel lblGestionarUsuarios2;
    private javax.swing.JLabel lblGestionarUsuarios3;
    private javax.swing.JLabel lblGestionarUsuarios4;
    private javax.swing.JLabel lblGestionarUsuarios5;
    private javax.swing.JLabel lblGestionarUsuarios6;
    private javax.swing.JLabel lblGestionarUsuarios7;
    private javax.swing.JLabel lblGestionarUsuarios8;
    private javax.swing.JLabel lblGestionarUsuarios9;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlHeader;
    // End of variables declaration//GEN-END:variables
}
